### ISSUE TITLE
Error during compile package

### ISSUE THREAD

**Issue by govlas** [teh-cmc/mmm#2]
$ go get -u github.com/teh-cmc/mmm
../../teh-cmc/mmm/mmm.go:135: undefined: syscall.MAP_ANONYMOUS

$ go version
go version go1.5.1 darwin/amd64

**Comment by teh-cmc** [comment]
That's because `OS X` uses `MAP_ANON` instead of `MAP_ANONYMOUS` (see https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man2/mmap.2.html).

I (or someone else) will fix that when I (or they) can; in the meantime, modifying line 135 to `syscall.MAP_ANON` should work for you!

**Comment by govlas** [comment]
So, I made PR to fix this problem.

**Comment by teh-cmc** [comment]
merged, thanks :)

**Comment by govlas** [comment]
You are welcome)
